# Generated by Django 5.2.6 on 2025-10-20 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=110)),
                ('region', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('exchange_rate_to_usd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('population', models.BigIntegerField()),
                ('median_age', models.DecimalField(decimal_places=3, max_digits=10)),
                ('population_growth_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('gdp', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gdp_growth_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trade_access_score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tariff_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('free_trade_agreements', models.IntegerField()),
                ('primary_revenue_source', models.TextField()),
                ('investment_climate', models.TextField()),
                ('fdi_trend', models.TextField()),
                ('labor_cost_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('political_stability_index', models.DecimalField(decimal_places=2, max_digits=4)),
                ('political_context', models.TextField()),
                ('economic_highlight', models.TextField()),
                ('economic_highlight_link', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DataLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(max_length=100)),
                ('link_url', models.TextField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konnectlysite.country')),
            ],
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('economic_contribution_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('growth_trend', models.TextField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konnectlysite.country')),
            ],
        ),
        migrations.CreateModel(
            name='InvestmentPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_pathway_1', models.TextField()),
                ('investment_pathway_2', models.TextField()),
                ('investment_pathway_3', models.TextField()),
                ('country_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='konnectlysite.country')),
            ],
        ),
    ]
