# Generated by Django 5.2.6 on 2025-10-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnectlysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Industry',
            new_name='Sectors',
        ),
    ]
