# Generated by Django 5.2.6 on 2025-12-19 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('konnectlysite', '0005_alter_country_currency_alter_country_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectors',
            name='country_id',
        ),
        migrations.DeleteModel(
            name='InvestmentPathway',
        ),
        migrations.DeleteModel(
            name='Sectors',
        ),
    ]
