CREATE TABLE "Country" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) UNIQUE NOT NULL,
  "region" varchar(100),
  "currency" varchar(50),
  "exchange_rate_to_usd" decimal(10,3),
  "population" bigint,
  "median_age" decimal(10,3),
  "population_growth_rate" decimal(4,2),
  "gdp" decimal(15,2),
  "gdp_growth_rate" decimal(5,2),
  "trade_access_score" decimal(4,2),
  "tariff_rate" decimal(5,2),
  "free_trade_agreements" int,
  "primary_revenue_source" text,
  "investment_climate" text,
  "fdi_trend" text,
  "labor_cost_usd" decimal(10,2),
  "political_stability_index" decimal(4,2),
  "political_context" text,
  "economic_highlight" text,
  "economic_highlight_link" text
);

CREATE TABLE "industry" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_id" int,
  "name" varchar(150),
  "economic_contribution_percent" decimal(5,2),
  "growth_trend" text
);

CREATE TABLE "investment_pathway" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_id" int,
  "investment_pathway_1" text,
  "investment_pathway_2" text,
  "investment_pathway_3" text
);

CREATE TABLE "data_links" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country_id" int,
  "link_type" varchar(100),
  "link_url" text
);

ALTER TABLE "industry" ADD FOREIGN KEY ("country_id") REFERENCES "Country" ("id");

ALTER TABLE "investment_pathway" ADD FOREIGN KEY ("country_id") REFERENCES "Country" ("id");

ALTER TABLE "data_links" ADD FOREIGN KEY ("country_id") REFERENCES "Country" ("id");
