/* 
Investments.jsx - 12/11/2025 -> COMPLETE BY PRESENTATION
Separate page for AI-generated investment pathway walkthrough set up with personal OpenAI API key.
- Displays AI-generated investment opportunity of given country selected
- Accesses country-page's API obtained country data
- Utilizes generateInvestments.js hook to generate AI response
*/

import React, { useEffect } from "react"; // only for console debug
import { useLocation } from "react-router-dom"; // used for passing data between pages
import { useGenerateInvestment } from "../hooks/generateInvestments";

export default function InvestmentPage() {
    const location = useLocation();
    const countryData = location.state?.countryData;  // maintains access to country data from CountryPage.jsx

    const { response, loading, error } = useGenerateInvestment(countryData);

    // Safety Check
    if (!countryData) {
        return <div style={{ padding: "40px", color: "white", background: "#111", minHeight: "100vh" }}>
            <h1>No country data available</h1>
        </div>;
    }
    // Debugging
    useEffect(() => {
        console.log("Investments page received countryData:", countryData);
    }, [countryData]);

    return (
        <>
            {/* Container for text display */}
            <div style={{
                minHeight: "100vh",
                height: "100vh",
                width: "100vw",
                background: "#1e293b",
                color: "white",
                padding: "60px 20px",
                alignItems: "center",
                justifyContent: "left",
                fontFamily: "system-ui, -apple-system, sans-serif",
            }}>
                {/* Title */}
                <h1 style={{
                    textAlign: "center",
                    fontSize: "3.2rem",
                    fontWeight: "700",
                    marginBottom: "60px",
                    letterSpacing: "-0.5px",
                }}>
                    Investment Opportunities in {countryData.name}
                </h1>

                {/* Main Content Card */}
                <div style={{
                    width: "100%",
                    maxWidth: "1200px",
                    margin: "0 auto",
                    background: "white",
                    color: "#1e293b",
                    borderRadius: "20px",
                    boxShadow: "0 25px 60px rgba(0, 0, 0, 0.5)",
                    overflow: "hidden",
                    padding: "60px 80px",  // generous inner padding
                }}>
                    {/* Loading State */}
                    {loading && (
                        <div style={{
                            padding: "80px 40px",
                            textAlign: "center",
                            fontSize: "1.4rem",
                            color: "#64748b",
                        }}>
                            <div style={{
                                display: "inline-block",
                                width: "40px",
                                height: "40px",
                                borderRadius: "50%",
                                marginBottom: "20px",
                            }}></div>
                            <p>Generating investment pathways...</p>
                        </div>
                    )}

                    {/* Response */}
                    {response && !loading && (
                        <div style={{
                            padding: "60px 80px",
                            lineHeight: "1.9",
                            fontSize: "1.15rem",
                            color: "#1e293b",
                        }}>
                            <pre style={{
                                whiteSpace: "pre-wrap",
                                fontFamily: "Geirgia, serif", //

                                margin: 0,
                            }}>
                                {response}
                            </pre>
                        </div>
                    )}
                </div>

                <p style={{
                    textAlign: "center",
                    marginTop: "60px",
                    fontSize: "1rem",
                    opacity: 0.7,
                }}>
                    Report generated by Grok AI | Data sourced from project database
                </p>
            </div>
        </>
    );

}